language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"
    - SYMFONY_VERSION="2.5.*"
    - SYMFONY_VERSION="2.6.*"

before_script:
    - composer require symfony/event-dispatcher:${SYMFONY_VERSION}

script: php vendor/bin/phpspec run
